/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author chris
 */
public class AdminMenuFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMenuFrame.class.getName());

    /**
     * Creates new form AdminMenuFrame
     */
    public AdminMenuFrame() {
        initComponents();
        
        // Centrar ventana
    this.setLocationRelativeTo(null);
    // Título de la ventana
    this.setTitle("Punto de Venta - Administrador");

    // Fondo gris claro como el menú principal
    getContentPane().setBackground(new java.awt.Color(245, 245, 245));

    // Colores para botones (puedes cambiar si quieres)
    java.awt.Color grisBoton = new java.awt.Color(180, 180, 180);
    java.awt.Color grisTexto = new java.awt.Color(30, 30, 30);

    btnAgregarProducto.setBackground(grisBoton);
    btnVerInventario.setBackground(grisBoton);
    btnRegresar.setBackground(grisBoton);

    btnAgregarProducto.setForeground(grisTexto);
    btnVerInventario.setForeground(grisTexto);
    btnRegresar.setForeground(grisTexto);

    btnAgregarProducto.setFocusPainted(false);
    btnVerInventario.setFocusPainted(false);
    btnRegresar.setFocusPainted(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSubtitulo = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnVerInventario = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTituloAdmin = new javax.swing.JLabel();
        lblLogotipoAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSubtitulo.setText("Seleccione una opcion:");

        btnAgregarProducto.setBackground(new java.awt.Color(180, 180, 180));
        btnAgregarProducto.setText("Agregar producto");
        btnAgregarProducto.setOpaque(true);
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnVerInventario.setBackground(new java.awt.Color(180, 180, 180));
        btnVerInventario.setText("Ver inventario");
        btnVerInventario.setOpaque(true);
        btnVerInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerInventarioActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        lblTituloAdmin.setBackground(new java.awt.Color(51, 51, 51));
        lblTituloAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloAdmin.setText("Administrador");

        lblLogotipoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logotipo Admin.png"))); // NOI18N
        lblLogotipoAdmin.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogotipoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogotipoAdmin)
                    .addComponent(lblTituloAdmin))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnAgregarProducto)
                                .addGap(53, 53, 53)
                                .addComponent(btnVerInventario))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(lblSubtitulo)))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegresar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerInventario)
                    .addComponent(btnAgregarProducto))
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
 * Evento que se ejecuta cuando el administrador hace clic en
 * "Agregar producto" desde el menú de administrador.
 * Abre la ventana AgregarProductoFrame y cierra el menú actual.
 */
    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
         AgregarProductoFrame agregar = new AgregarProductoFrame();
    agregar.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       // Volver al menú principal
    vista.MenuPrincipalFrame menu = new vista.MenuPrincipalFrame();
    menu.setVisible(true);
    this.dispose(); // Cierra esta ventana
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnVerInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerInventarioActionPerformed
       VerInventarioFrame verInv = new VerInventarioFrame();
    verInv.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnVerInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminMenuFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerInventario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogotipoAdmin;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTituloAdmin;
    // End of variables declaration//GEN-END:variables
}
