/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.awt.Color;
import javax.swing.JOptionPane;
import com.mycompany.proyecto_final.Carrito;
import com.mycompany.proyecto_final.Cliente;
import com.mycompany.proyecto_final.Pago;
import com.mycompany.proyecto_final.PagoTarjeta;
import com.mycompany.proyecto_final.PagoPayPal;
import com.mycompany.proyecto_final.PagoEfectivo;
import com.mycompany.proyecto_final.ProcesadorPagos;
import com.mycompany.proyecto_final.Producto;

/**
 *
 * @author chris
 */
/**
 * Ventana para que el cliente elija la forma de pago.
 * Usa polimorfismo con la jerarquía Pago (PagoTarjeta, PagoPayPal, PagoEfectivo).
 */
public class PagoFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PagoFrame.class.getName());

     /** Cliente que está realizando el pago. */
    private Cliente cliente;

    /** Carrito cuyos productos se van a pagar. */
    private Carrito carrito;

    /** Total calculado del carrito. */
    private double total;
    // Constructor principal que recibe el cliente y su carrito.
     
    public PagoFrame(Cliente cliente, Carrito carrito) {
        initComponents();
        this.cliente = cliente;
        this.carrito = carrito;

        // Calculamos el total del carrito
        this.total = carrito.calcularTotal();

        // Centrar la ventana
        this.setLocationRelativeTo(null);

        // Título de la ventana con el nombre del cliente
        this.setTitle("Pago - Chapi's (" + cliente.getNombre() + ")");

        // Color de fondo gris claro (igual que el resto)
        getContentPane().setBackground(new Color(245, 245, 245));

        // Mostramos el total formateado
        lblTotalValor.setText(String.format("$ %.2f", total));
    }
    /**
     * Constructor sin parámetros, solo para pruebas rápidas.
     */
    public PagoFrame() {
        this(new Cliente("Invitado", "invitado", ""), new Carrito());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalTexto = new javax.swing.JLabel();
        lblTotalValor = new javax.swing.JLabel();
        btnPayPal = new javax.swing.JButton();
        btnEfectivo = new javax.swing.JButton();
        btnTarjeta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogotipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTotalTexto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalTexto.setText("Total a pagar:");

        lblTotalValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalValor.setText("$0.00");

        btnPayPal.setBackground(new java.awt.Color(204, 204, 204));
        btnPayPal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPayPal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pago PayPal.png"))); // NOI18N
        btnPayPal.setText("PayPal");
        btnPayPal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayPalActionPerformed(evt);
            }
        });

        btnEfectivo.setBackground(new java.awt.Color(204, 204, 204));
        btnEfectivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lotipo efectivo.png"))); // NOI18N
        btnEfectivo.setText("Efectivo");
        btnEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectivoActionPerformed(evt);
            }
        });

        btnTarjeta.setBackground(new java.awt.Color(204, 204, 204));
        btnTarjeta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logotipo tarjeta.png"))); // NOI18N
        btnTarjeta.setText("Tarjeta");
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Selecciona un metodo de pago:");

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Ventana de Pago");

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logotipo1.png"))); // NOI18N
        lblLogotipo.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblLogotipo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalTexto)
                                .addGap(14, 14, 14)
                                .addComponent(lblTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnPayPal)
                                .addGap(18, 18, 18)
                                .addComponent(btnEfectivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTarjeta)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalTexto)
                    .addComponent(lblTotalValor))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayPal)
                    .addComponent(btnEfectivo)
                    .addComponent(btnTarjeta))
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Evento que se ejecuta cuando el usuario hace clic en "Tarjeta".
     * Pide los datos de la tarjeta, crea un PagoTarjeta y lo procesa
     * de forma polimórfica.
     */
    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
        // Pedimos los datos de la tarjeta con JOptionPane
        String numero = JOptionPane.showInputDialog(this, "Número de la tarjeta:");
        if (numero == null || numero.trim().isEmpty()) {
            return; // Canceló o no ingresó nada
        }

        String titular = JOptionPane.showInputDialog(this, "Nombre del titular:");
        if (titular == null || titular.trim().isEmpty()) {
            return;
        }

        String cvv = JOptionPane.showInputDialog(this, "CVV (3 dígitos):");
        if (cvv == null || cvv.trim().isEmpty()) {
            return;
        }

        String fecha = JOptionPane.showInputDialog(this, "Fecha de expiración (MM/AA):");
        if (fecha == null || fecha.trim().isEmpty()) {
            return;
        }

        // Creamos un objeto PagoTarjeta (subclase de Pago)
        Pago pago = new PagoTarjeta(total, numero, titular, cvv, fecha);

        // Procesamos el pago de forma polimórfica
        String resultado = ProcesadorPagos.procesarPago(pago);

        // Mostramos el mensaje devuelto por realizarPago()
        JOptionPane.showMessageDialog(
                this,
                resultado,
                "Pago exitoso",
                JOptionPane.INFORMATION_MESSAGE
        );

        finalizarCompra();
    }//GEN-LAST:event_btnTarjetaActionPerformed
/**
     * Evento que se ejecuta cuando el usuario hace clic en "PayPal".
     * Pide correo y contraseña, crea un PagoPayPal y lo procesa.
     */
    private void btnPayPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayPalActionPerformed
        String correo = JOptionPane.showInputDialog(this, "Correo de PayPal:");
        if (correo == null || correo.trim().isEmpty()) {
            return;
        }

        String contrasena = JOptionPane.showInputDialog(this, "Contraseña de PayPal:");
        if (contrasena == null || contrasena.trim().isEmpty()) {
            return;
        }

        // Creamos un objeto PagoPayPal
        Pago pago = new PagoPayPal(total, correo, contrasena);

        // Procesamos el pago polimórficamente
        String resultado = ProcesadorPagos.procesarPago(pago);

        JOptionPane.showMessageDialog(
                this,
                resultado,
                "Pago exitoso",
                JOptionPane.INFORMATION_MESSAGE
        );

        finalizarCompra();
    }//GEN-LAST:event_btnPayPalActionPerformed
/**
     * Evento que se ejecuta cuando el usuario hace clic en "Efectivo".
     * Crea un PagoEfectivo y lo procesa sin pedir más datos.
     */
    private void btnEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivoActionPerformed
        // Creamos un pago en efectivo
        Pago pago = new PagoEfectivo(total);

        // Procesamos polimórficamente
        String resultado = ProcesadorPagos.procesarPago(pago);

        JOptionPane.showMessageDialog(
                this,
                resultado,
                "Pago registrado",
                JOptionPane.INFORMATION_MESSAGE
        );

        finalizarCompra();
    }//GEN-LAST:event_btnEfectivoActionPerformed
/**
     * Evento que se ejecuta cuando el usuario hace clic en "Cancelar".
     * Regresa a la ventana del carrito sin realizar ningún pago.
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
          // Regresamos al carrito
        CarritoFrame cf = new CarritoFrame(cliente, carrito);
        cf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
 /**
     * Método auxiliar que se ejecuta después de un pago exitoso.
     * Vacía el carrito, agradece al cliente y regresa al menú de cliente.
     */
    private void finalizarCompra() {
        // 1. Descontar el stock del inventario según lo comprado
    for (Carrito.LineaCarrito linea : carrito.getLineas()) {
        Producto p = linea.getProducto();
        int cantidadComprada = linea.getCantidad();

        int stockActual = p.getStock();
        int nuevoStock = stockActual - cantidadComprada;

        if (nuevoStock < 0) {
            nuevoStock = 0; // por seguridad, aunque no debería pasar
        }

        p.setStock(nuevoStock);
    }

    // 2. Vaciar el carrito después del pago
    carrito.vaciar();

    // 3. Mensaje de agradecimiento
    JOptionPane.showMessageDialog(
            this,
            "Gracias por tu compra en Chapi's, " + cliente.getNombre() + "!",
            "Compra completada",
            JOptionPane.INFORMATION_MESSAGE
    );

    // 4. Volver al menú de cliente
    ClienteMenuFrame cm = new ClienteMenuFrame(cliente);
    cm.setVisible(true);
    this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PagoFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEfectivo;
    private javax.swing.JButton btnPayPal;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalTexto;
    private javax.swing.JLabel lblTotalValor;
    // End of variables declaration//GEN-END:variables
}
