/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import com.mycompany.proyecto_final.Sistema;
import com.mycompany.proyecto_final.Producto;


/**
 *
 * @author chris
 */
/**
 * Ventana para agregar nuevos productos al inventario de Chapi's.
 */
public class AgregarProductoFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarProductoFrame.class.getName());

    /**
     * Creates new form AgregarProductoFrame
     */
    public AgregarProductoFrame() {
        initComponents();
        
        // Centrar la ventana en la pantalla
        this.setLocationRelativeTo(null);

        // Título de la ventana
        this.setTitle("Chapi's - Agregar producto");

        // Color de fondo general (gris muy claro, igual que otros frames)
        getContentPane().setBackground(new Color(245, 245, 245));

        // Opcional: poner un pequeño borde al formulario completo
        getRootPane().setBorder(
                BorderFactory.createLineBorder(new Color(200, 200, 200), 1)
        );

        // Estilo básico para botones (puedes ajustarlo a tu gusto)
        Color grisBoton = new Color(180, 180, 180);
        Color grisTexto = new Color(30, 30, 30);

        btnGuardar.setBackground(grisBoton);
        btnLimpiar.setBackground(grisBoton);
        btnCancelar.setBackground(grisBoton);

        btnGuardar.setForeground(grisTexto);
        btnLimpiar.setForeground(grisTexto);
        btnCancelar.setForeground(grisTexto);

        btnGuardar.setFocusPainted(false);
        btnLimpiar.setFocusPainted(false);
        btnCancelar.setFocusPainted(false);
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogotipoAdmin2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setBackground(new java.awt.Color(204, 204, 204));
        lblId.setText("ID del producto:");
        lblId.setOpaque(true);

        lblNombre.setBackground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("Nombre del producto:");
        lblNombre.setOpaque(true);

        lblPrecio.setBackground(new java.awt.Color(204, 204, 204));
        lblPrecio.setText("Precio:");
        lblPrecio.setOpaque(true);

        lblStock.setBackground(new java.awt.Color(204, 204, 204));
        lblStock.setText("Numero de unidades:");
        lblStock.setOpaque(true);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setText("Cancelar/Regresar");
        btnCancelar.setOpaque(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Agregar/Modificar stock");

        lblLogotipoAdmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logotipo Admin.png"))); // NOI18N
        lblLogotipoAdmin2.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lblLogotipoAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogotipoAdmin2)
                    .addComponent(lblTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecio)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Evento que se ejecuta cuando el usuario hace clic en "Cancelar / Regresar".
 * Cierra esta ventana y regresa al menú del administrador.
 */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       // Creamos y mostramos nuevamente el menú del administrador
    AdminMenuFrame adminMenu = new AdminMenuFrame();
    adminMenu.setVisible(true);

    // Cerramos la ventana actual
    this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed
/**
 * Evento que se ejecuta cuando el usuario hace clic en el botón "Guardar".
 * Toma los datos de los campos de texto, los valida y, si son correctos,
 * crea un nuevo producto y lo agrega al inventario del sistema.
 */
    /**
 * Limpia el contenido de todos los campos de texto del formulario.
 * Se utiliza después de guardar un producto o cuando el usuario
 * hace clic en el botón "Limpiar".
 */
private void limpiarCampos() {
    txtId.setText("");
    txtNombre.setText("");
    txtPrecio.setText("");
    txtStock.setText("");

    // Colocamos el cursor nuevamente en el campo ID
    txtId.requestFocus();
}
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
        // 1. Leemos y validamos que no estén vacíos
        String textoId = txtId.getText().trim();
        String nombre = txtNombre.getText().trim();
        String textoPrecio = txtPrecio.getText().trim();
        String textoStock = txtStock.getText().trim();

        if (textoId.isEmpty() || nombre.isEmpty() || textoPrecio.isEmpty() || textoStock.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor completa todos los campos.",
                    "Campos incompletos",
                    JOptionPane.WARNING_MESSAGE
            );
            return; // No seguimos si falta algo
        }

        // 2. Convertimos ID, precio y stock a números
        int id = Integer.parseInt(textoId);       // Puede lanzar NumberFormatException
        double precio = Double.parseDouble(textoPrecio);
        int stock = Integer.parseInt(textoStock);

        // 3. Revisamos si ya existe un producto con ese ID en el inventario
       Producto existente = Sistema.inventario.buscarPorId(id);

if (existente != null) {
    // Si el ID ya existe, preguntamos si se desea sumar stock
    int opcion = JOptionPane.showConfirmDialog(
            this,
            "Ya existe un producto con el ID " + id + ":\n"
            + "Nombre: " + existente.getNombre() + "\n"
            + "Stock actual: " + existente.getStock() + "\n\n"
            + "¿Deseas agregar " + stock + " unidades más a este producto?",
            "Producto existente",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
    );

    if (opcion == JOptionPane.YES_OPTION) {
        // Aumentamos el stock del producto existente
        int nuevoStock = existente.getStock() + stock;
        existente.setStock(nuevoStock);

        // Opcional: actualizar nombre y precio si cambiaron
        existente.setNombre(nombre);
        existente.setPrecio(precio);

        JOptionPane.showMessageDialog(
                this,
                "Stock actualizado correctamente.\n"
                + "Nuevo stock: " + nuevoStock,
                "Stock actualizado",
                JOptionPane.INFORMATION_MESSAGE
        );

        // Limpiamos los campos para la siguiente operación
        limpiarCampos();
    }

    // Sea que el admin acepte o no, ya no creamos un producto nuevo
    return;
        }

        // 4. Creamos el nuevo producto
        Producto nuevo = new Producto(id, nombre, precio, stock);

        // 5. Lo agregamos al inventario central del sistema
        Sistema.inventario.agregarProducto(nuevo);

        // 6. Mostramos mensaje de éxito
        JOptionPane.showMessageDialog(
                this,
                "Producto agregado correctamente al inventario de Chapi's.",
                "Producto registrado",
                JOptionPane.INFORMATION_MESSAGE
        );

        // 7. Limpiamos los campos para que pueda agregar otro producto
        limpiarCampos();

    } catch (NumberFormatException ex) {
        // Ocurre si el usuario escribe letras donde deben ir números
        JOptionPane.showMessageDialog(
                this,
                "ID, precio y stock deben ser valores numéricos válidos.",
                "Error de formato",
                JOptionPane.ERROR_MESSAGE
        );
    } catch (Exception ex) {
        // Cualquier otro error inesperado
        JOptionPane.showMessageDialog(
                this,
                "Ocurrió un error al guardar el producto: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    }//GEN-LAST:event_btnGuardarActionPerformed
/**
 * Evento que se ejecuta cuando el usuario hace clic en "Limpiar".
 * Simplemente llama al método limpiarCampos() para vaciar las cajas de texto.
 */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgregarProductoFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLogotipoAdmin2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
