/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.proyecto_final.Carrito;
import com.mycompany.proyecto_final.Cliente;
import com.mycompany.proyecto_final.Producto;
/**
 *
 * @author chris
 */
public class CarritoFrame extends javax.swing.JFrame {
    
    /** Cliente actual dueño del carrito. */
    private Cliente cliente;

    /** Carrito de compras actual. */
    private Carrito carrito;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CarritoFrame.class.getName());

    /**
     * Constructor que recibe el cliente actual y su carrito.
     *
     * @param cliente Cliente que está realizando la compra.
     * @param carrito Carrito con los productos seleccionados.
     */
    public CarritoFrame(Cliente cliente, Carrito carrito) {
        initComponents();
        this.cliente = cliente;
        this.carrito = carrito;

        // Centrar la ventana
        this.setLocationRelativeTo(null);

        // Título con nombre del cliente
        this.setTitle("Carrito de " + cliente.getNombre() + " - Chapi's");

        // Color de fondo coherente con el resto de la app
        getContentPane().setBackground(new Color(245, 245, 245));

        // Cargar la información del carrito en la tabla
        cargarTablaCarrito();
        actualizarTotal();
    }

    /**
     * Constructor sin parámetros.
     * Solo para pruebas rápidas. Crea un cliente invitado y un carrito vacío.
     */
    public CarritoFrame() {
        this(new Cliente("Invitado", "invitado", ""), new Carrito());
    }
/**
     * Llena la tabla "tablaCarrito" con los productos que
     * el cliente tiene actualmente en su carrito.
     *
     * NOTA: Ajusta este método de acuerdo a cómo esté implementado
     * tu clase Carrito (por ejemplo, lista de líneas, mapa, etc.).
     */
    private void cargarTablaCarrito() {
        DefaultTableModel modelo = (DefaultTableModel) tablaCarrito.getModel();
        modelo.setRowCount(0); // Limpiar filas

        // Ejemplo asumiendo que Carrito tiene un método getLineas()
        // que devuelve una lista de objetos LineaCarrito con:
        // - getProducto()
        // - getCantidad()
        for (Carrito.LineaCarrito linea : carrito.getLineas()) {
            Producto p = linea.getProducto();
            int cantidad = linea.getCantidad();
            double subtotal = p.getPrecio() * cantidad;

            Object[] fila = new Object[5];
            fila[0] = p.getId();
            fila[1] = p.getNombre();
            fila[2] = p.getPrecio();
            fila[3] = cantidad;
            fila[4] = subtotal;

            modelo.addRow(fila);
        }

        tablaCarrito.setModel(modelo);
    }
    /**
     * Calcula el total del carrito sumando los subtotales
     * de cada línea y lo muestra en la etiqueta lblTotalValor.
     */
    private void actualizarTotal() {
        double total = 0.0;

        DefaultTableModel modelo = (DefaultTableModel) tablaCarrito.getModel();
        int filas = modelo.getRowCount();

        for (int i = 0; i < filas; i++) {
            double subtotal = (double) modelo.getValueAt(i, 4); // Columna "Subtotal"
            total += subtotal;
        }

        lblTotalValor.setText(String.format("$ %.2f", total));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalTexto = new javax.swing.JLabel();
        lblTotalValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        btnQuitar = new javax.swing.JButton();
        btnProcederPago = new javax.swing.JButton();
        btnVaciar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogotipoCarrito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTotalTexto.setText("Total:");

        lblTotalValor.setText("$0.00");

        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tablaCarrito);

        btnQuitar.setBackground(new java.awt.Color(204, 204, 204));
        btnQuitar.setText("Quitar producto");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnProcederPago.setBackground(new java.awt.Color(204, 204, 204));
        btnProcederPago.setText("Pagar");
        btnProcederPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcederPagoActionPerformed(evt);
            }
        });

        btnVaciar.setBackground(new java.awt.Color(204, 204, 204));
        btnVaciar.setText("Vaciar carrito");
        btnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Carrito de compras");

        lblLogotipoCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logotipo carrito.png"))); // NOI18N
        lblLogotipoCarrito.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogotipoCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblLogotipoCarrito))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnQuitar)
                                .addGap(51, 51, 51)
                                .addComponent(btnProcederPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalValor))
                            .addComponent(btnVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitar)
                    .addComponent(btnProcederPago)
                    .addComponent(lblTotalTexto)
                    .addComponent(lblTotalValor))
                .addGap(18, 18, 18)
                .addComponent(btnVaciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int filaSeleccionada = tablaCarrito.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecciona un producto del carrito para quitarlo.",
                    "Ninguna fila seleccionada",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Obtenemos el ID del producto desde la tabla
        int idProducto = (int) tablaCarrito.getValueAt(filaSeleccionada, 0);
        Producto producto = com.mycompany.proyecto_final.Sistema.inventario.buscarPorId(idProducto);

        // Aquí asumimos que Carrito tiene un método quitarProducto(Producto p)
        carrito.quitarProducto(producto);

        // Volvemos a cargar la tabla y el total
        cargarTablaCarrito();
        actualizarTotal();
    }//GEN-LAST:event_btnQuitarActionPerformed
/**
     * Evento que se ejecuta cuando el cliente hace clic en
     * "Vaciar carrito". Elimina todos los productos del carrito.
     */
    private void btnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarActionPerformed
         int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que deseas vaciar todo el carrito?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            // Asumimos que Carrito tiene un método vaciar()
            carrito.vaciar();

            cargarTablaCarrito();
            actualizarTotal();
        }
    }//GEN-LAST:event_btnVaciarActionPerformed
/**
     * Evento que se ejecuta cuando el cliente hace clic en "Regresar".
     * Vuelve a la ventana de Cliente, manteniendo el mismo carrito.
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      ClienteMenuFrame clienteFrame = new ClienteMenuFrame(cliente, carrito);
      clienteFrame.setVisible(true);
      this.dispose();  
    }//GEN-LAST:event_btnRegresarActionPerformed
/**
     * Evento que se ejecuta cuando el cliente hace clic
     * en "Proceder al pago".
     * Más adelante aquí abriremos la ventana que implementa
     * el polimorfismo de la clase abstracta Pago
     * (PagoTarjeta, PagoPayPal, PagoEfectivo).
     */
    private void btnProcederPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcederPagoActionPerformed
      if (carrito.getLineas().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Tu carrito está vacío. Agrega productos antes de pagar.",
                "Carrito vacío",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    PagoFrame pagoFrame = new PagoFrame(cliente, carrito);
    pagoFrame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnProcederPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CarritoFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcederPago;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVaciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogotipoCarrito;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalTexto;
    private javax.swing.JLabel lblTotalValor;
    private javax.swing.JTable tablaCarrito;
    // End of variables declaration//GEN-END:variables
}
