/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.proyecto_final.Sistema;
import com.mycompany.proyecto_final.Producto;
import com.mycompany.proyecto_final.Carrito;
import com.mycompany.proyecto_final.Cliente;

/**
 *
 * @author chris
 */
 /**
 * Ventana principal para el cliente.
 * Aquí el cliente puede ver el inventario de productos tecnológicos
 * de Chapi's y agregar productos a su carrito de compras.
 */
public class ClienteMenuFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteMenuFrame.class.getName());
// Carrito asociado a esta sesión de cliente
private Carrito carrito;
//cliente actual
        private Cliente cliente;

    /**
     * Constructor que recibe el cliente actual y carrito ya existente
     *
     * @param cliente Cliente que está usando la aplicación.
     */
    public ClienteMenuFrame(Cliente cliente, Carrito carrito) {
        initComponents();
        this.cliente = cliente;
    this.carrito = carrito; //Conservamos los productos
    
    this.setLocationRelativeTo(null);
    this.setTitle("Chapi's - Zona Cliente (" + cliente.getNombre() + ")");
    getContentPane().setBackground(new java.awt.Color(245, 245, 245));

    cargarTablaProductosCliente();
    }
    public ClienteMenuFrame(Cliente cliente) {
    this(cliente, Sistema.obtenerCarritoParaCliente(cliente));
//Aqui usamos el carrito propio de cada usuario que se almaceno en Sistema

}

/**
 * Constructor sin parámetros: cliente invitado y carrito nuevo.
 */
public ClienteMenuFrame() {
    this(new Cliente("Invitado", "invitado", ""));
}

   
   
    /**
 * Llena la tabla "tablaProductosCliente" con los productos
 * que existen actualmente en el inventario del sistema.
 */
private void cargarTablaProductosCliente() {
    // Obtenemos el modelo de la tabla
    DefaultTableModel modelo = (DefaultTableModel) tablaProductosCliente.getModel();

    // Limpiamos filas anteriores
    modelo.setRowCount(0);

    // Recorremos los productos del inventario de Chapi's
    for (Producto p : Sistema.inventario.getProductos()) {
        Object[] fila = new Object[4];
        fila[0] = p.getId();
        fila[1] = p.getNombre();
        fila[2] = p.getPrecio();
        fila[3] = p.getStock();

        modelo.addRow(fila);
    }

    tablaProductosCliente.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductosCliente = new javax.swing.JTable();
        btnAgregarAlCarrito = new javax.swing.JButton();
        btnVerCarrito = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Productos disponibles:");

        tablaProductosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tablaProductosCliente);

        btnAgregarAlCarrito.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarAlCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logotipo carrito.png"))); // NOI18N
        btnAgregarAlCarrito.setText("Agregar al carrito");
        btnAgregarAlCarrito.setOpaque(true);
        btnAgregarAlCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlCarritoActionPerformed(evt);
            }
        });

        btnVerCarrito.setBackground(new java.awt.Color(204, 204, 204));
        btnVerCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logotipo tarjeta.png"))); // NOI18N
        btnVerCarrito.setText("Ver carrito/Pagar");
        btnVerCarrito.setOpaque(true);
        btnVerCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCarritoActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setText("Regresar");
        btnRegresar.setOpaque(true);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Chapi's ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logotipo1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnVerCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAgregarAlCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegresar)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarAlCarrito)
                        .addGap(47, 47, 47)
                        .addComponent(btnVerCarrito)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Evento que se ejecuta cuando el cliente hace clic en
 * "Ver carrito / Pagar".
 * Más adelante aquí abriremos una ventana para:
 *  - Ver el contenido del carrito
 *  - Elegir la forma de pago
 */
    private void btnVerCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCarritoActionPerformed
          CarritoFrame carritoFrame = new CarritoFrame(cliente, carrito);
    carritoFrame.setVisible(true);
    this.dispose(); // Cerramos la ventana actual para no dejar muchas abiertas
    }//GEN-LAST:event_btnVerCarritoActionPerformed
/**
 * Evento que se ejecuta cuando el cliente hace clic en "Agregar al carrito".
 * Toma el producto seleccionado en la tabla y pregunta cuántas unidades
 * desea agregar al carrito, validando que haya stock suficiente.
 */
    private void btnAgregarAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlCarritoActionPerformed
      // 1. Verificamos que haya una fila seleccionada en la tabla
    int filaSeleccionada = tablaProductosCliente.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Por favor selecciona un producto de la tabla.",
                "Ningún producto seleccionado",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // 2. Obtenemos el ID del producto desde la tabla (columna 0)
    int idProducto = (int) tablaProductosCliente.getValueAt(filaSeleccionada, 0);

    // 3. Buscamos el producto real en el inventario usando el ID
    Producto productoSeleccionado = Sistema.inventario.buscarPorId(idProducto);

    if (productoSeleccionado == null) {
        JOptionPane.showMessageDialog(
                this,
                "No se encontró el producto en el inventario.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // 4. Pedimos al cliente la cantidad que desea agregar
    String textoCantidad = JOptionPane.showInputDialog(
            this,
            "¿Cuántas unidades de \"" + productoSeleccionado.getNombre() + "\" deseas agregar al carrito?",
            "Cantidad",
            JOptionPane.QUESTION_MESSAGE
    );

    // Si el cliente cancela el cuadro de diálogo
    if (textoCantidad == null) {
        return;
    }

    try {
        int cantidad = Integer.parseInt(textoCantidad);

        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "La cantidad debe ser mayor que cero.",
                    "Cantidad inválida",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // 5. Validamos que haya stock suficiente en el inventario
        if (cantidad > productoSeleccionado.getStock()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay suficiente stock.\nStock disponible: " + productoSeleccionado.getStock(),
                    "Stock insuficiente",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // 6. Agregamos el producto al carrito (sin modificar aún el stock real del inventario)
        carrito.agregarProducto(productoSeleccionado, cantidad);

        JOptionPane.showMessageDialog(
                this,
                "Se agregaron " + cantidad + " unidades de \"" 
                + productoSeleccionado.getNombre() + "\" al carrito.",
                "Producto agregado",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(
                this,
                "La cantidad debe ser un número entero.",
                "Error de formato",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnAgregarAlCarritoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuPrincipalFrame menu = new MenuPrincipalFrame();
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteMenuFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlCarrito;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaProductosCliente;
    // End of variables declaration//GEN-END:variables
}
