/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import vista.AdminMenuFrame;
import javax.swing.JOptionPane;
import com.mycompany.proyecto_final.Sistema;
import javax.swing.JOptionPane;
import com.mycompany.proyecto_final.Sistema;
import com.mycompany.proyecto_final.Cliente;
import vista.ClienteMenuFrame;
/**
 *
 * @author chris
 */
public class MenuPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName());

    /**
     * Creates new form MenuPrincipalFrame
     */
    public MenuPrincipalFrame() {
        initComponents();
         // Centrar la ventana en la pantalla
    this.setLocationRelativeTo(null);

    // Título de la ventana (por si no lo pusiste en Properties)
    this.setTitle("Punto de Venta - Menú Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdmin = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblIniciarSesion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punto de Venta - Menu Principal");
        setBackground(new java.awt.Color(236, 236, 236));
        setResizable(false);

        btnAdmin.setBackground(new java.awt.Color(180, 180, 180));
        btnAdmin.setText("Administrador");
        btnAdmin.setBorder(new javax.swing.border.MatteBorder(null));
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnCliente.setBackground(new java.awt.Color(180, 180, 180));
        btnCliente.setText("Cliente");
        btnCliente.setBorder(new javax.swing.border.MatteBorder(null));
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalir.setOpaque(true);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblIniciarSesion.setBackground(new java.awt.Color(0, 0, 0));
        lblIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(102, 102, 102));
        lblIniciarSesion.setText("Iniciar sesion como:");

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Punto de Venta \"Chapi's\"");

        lblBienvenido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBienvenido.setText("Bienvenido a:");

        lblLogo.setBackground(new java.awt.Color(245, 245, 245));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logotipo1.png"))); // NOI18N
        lblLogo.setText("jLabel3");
        lblLogo.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBienvenido)
                    .addComponent(lblTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBienvenido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitulo)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 515, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(lblIniciarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIniciarSesion)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
   // 1. Pedimos el nombre de usuario para el administrador
    String usuario = JOptionPane.showInputDialog(
            this,
            "Ingresa el usuario de administrador:",
            "Login Administrador",
            JOptionPane.QUESTION_MESSAGE
    );

    // Si el usuario presiona "Cancelar" o cierra la ventana, usuario será null
    if (usuario == null) {
        // Canceló el login, no hacemos nada
        return;
    }

    // 2. Pedimos la contraseña (con cuadro de texto normal; para algo más seguro se usaría JPasswordField)
    String password = JOptionPane.showInputDialog(
            this,
            "Ingresa la contraseña:",
            "Login Administrador",
            JOptionPane.QUESTION_MESSAGE
    );

    if (password == null) {
        // Canceló la contraseña, no hacemos nada
        return;
    }

    // 3. Validamos las credenciales usando la clase Sistema
    boolean esValido = Sistema.validarCredencialesAdmin(usuario, password);

    if (esValido) {
        // 4. Si las credenciales son correctas, mostramos mensaje de bienvenida
        JOptionPane.showMessageDialog(
                this,
                "Acceso concedido. Bienvenido, administrador.",
                "Login correcto",
                JOptionPane.INFORMATION_MESSAGE
        );

        // Abrimos el menú del administrador
        AdminMenuFrame admin = new AdminMenuFrame();
        admin.setVisible(true);

        // Cerramos el menú principal
        this.dispose();

    } else {
        // 5. Si las credenciales NO son correctas, mostramos mensaje de error
        JOptionPane.showMessageDialog(
                this,
                "Usuario o contraseña incorrectos.\nNo tienes permiso de administrador.",
                "Error de autenticación",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       int opcion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que deseas salir?",
            "Confirmar salida",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (opcion == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnSalirActionPerformed
/**
 * Muestra un pequeño flujo de registro para un nuevo cliente.
 * Pide nombre, usuario y contraseña, crea un objeto Cliente
 * y lo registra en el sistema.
 *
 * @return el Cliente registrado, o null si el usuario canceló.
 */
private Cliente registrarNuevoCliente() {
    String nombre = JOptionPane.showInputDialog(
            this,
            "Ingresa tu nombre:",
            "Registro de cliente",
            JOptionPane.QUESTION_MESSAGE
    );

    if (nombre == null || nombre.trim().isEmpty()) {
        return null; // Canceló o no puso nombre
    }

    String usuario = JOptionPane.showInputDialog(
            this,
            "Elige un nombre de usuario:",
            "Registro de cliente",
            JOptionPane.QUESTION_MESSAGE
    );

    if (usuario == null || usuario.trim().isEmpty()) {
        return null;
    }

    // Validamos que el usuario no exista ya
    if (Sistema.buscarClientePorUsuario(usuario) != null) {
        JOptionPane.showMessageDialog(
                this,
                "Ese nombre de usuario ya está registrado. Elige otro.",
                "Usuario en uso",
                JOptionPane.WARNING_MESSAGE
        );
        return null;
    }

    String password = JOptionPane.showInputDialog(
            this,
            "Elige una contraseña:",
            "Registro de cliente",
            JOptionPane.QUESTION_MESSAGE
    );

    if (password == null || password.trim().isEmpty()) {
        return null;
    }

    // Creamos el nuevo cliente
    Cliente nuevo = new Cliente(nombre.trim(), usuario.trim(), password.trim());

    // Lo registramos en el sistema
    Sistema.registrarCliente(nuevo);

    JOptionPane.showMessageDialog(
            this,
            "Registro exitoso. ¡Bienvenido a Chapi's, " + nombre + "!",
            "Cliente registrado",
            JOptionPane.INFORMATION_MESSAGE
    );

    return nuevo;
}
/**
 * Pide usuario y contraseña e intenta iniciar sesión con un cliente ya registrado.
 *
 * @return el Cliente si las credenciales son correctas, o null si no.
 */
private Cliente iniciarSesionCliente() {
    String usuario = JOptionPane.showInputDialog(
            this,
            "Ingresa tu nombre de usuario:",
            "Inicio de sesión",
            JOptionPane.QUESTION_MESSAGE
    );

    if (usuario == null || usuario.trim().isEmpty()) {
        return null;
    }

    Cliente existente = Sistema.buscarClientePorUsuario(usuario.trim());

    if (existente == null) {
        JOptionPane.showMessageDialog(
                this,
                "No existe ningún cliente registrado con ese usuario.",
                "Usuario no encontrado",
                JOptionPane.ERROR_MESSAGE
        );
        return null;
    }

    String password = JOptionPane.showInputDialog(
            this,
            "Ingresa tu contraseña:",
            "Inicio de sesión",
            JOptionPane.QUESTION_MESSAGE
    );

    if (password == null) {
        return null;
    }

    if (!existente.getPassword().equals(password)) {
        JOptionPane.showMessageDialog(
                this,
                "Contraseña incorrecta.",
                "Error de autenticación",
                JOptionPane.ERROR_MESSAGE
        );
        return null;
    }

    JOptionPane.showMessageDialog(
            this,
            "Bienvenido de nuevo, " + existente.getNombre() + "!",
            "Inicio de sesión correcto",
            JOptionPane.INFORMATION_MESSAGE
    );

    return existente;
}
    /**
 * Evento que se ejecuta cuando el usuario hace clic en el botón "Cliente".
 * Aquí se le da la opción de:
 *  - Registrarse como nuevo cliente,
 *  - Iniciar sesión si ya está registrado,
 *  - O continuar como invitado.
 */
    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
      // Opciones que se mostrarán al usuario
    String[] opciones = { "Registrarse", "Iniciar sesión", "Continuar como invitado", "Cancelar" };

    int seleccion = JOptionPane.showOptionDialog(
            this,
            "¿Cómo deseas continuar en Chapi's?",
            "Zona Cliente",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]
    );

    // Si cierra el cuadro o elige "Cancelar"
    if (seleccion == -1 || seleccion == 3) {
        return;
    }

    Cliente clienteActual = null;

    switch (seleccion) {
        case 0: // Registrarse
            clienteActual = registrarNuevoCliente();
            break;
        case 1: // Iniciar sesión
            clienteActual = iniciarSesionCliente();
            break;
        case 2: // Invitado
            // Creamos un cliente "temporal" solo con nombre genérico
            clienteActual = new Cliente("Invitado", "invitado", "");
            break;
    }

    // Si por alguna razón no se obtuvo un cliente (por ejemplo, canceló en medio)
    if (clienteActual == null) {
        return;
    }

    // Abrimos la zona de cliente pasando el clienteActual
    ClienteMenuFrame clienteFrame = new ClienteMenuFrame(clienteActual);
    clienteFrame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
